services:
  rstudio:
    container_name: zj-rstudio-server
    image: zj-rstudio-image:latest 
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "50006:8787"
    environment:
      PASSWORD: zj109965
      USERID: ${UID}
      GROUPID: ${GID}
      HOME: /home/jzhang
    volumes:
      - /data/jzhang:/data/jzhang:rw
      - /home/jzhang:/home/jzhang:rw
      - /data/jzhang/rstudio/jzhang:/home/jzhang:rw